import './global.css';
import { ThemeProvider } from '@/components/providers/theme-provider';

export const metadata = {
  title: 'Welcome to life-ops-dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children} 
        </ThemeProvider>
      </body>
    </html>
  );
}
